apiVersion: v2
name: marcolongo-cloud
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: '1.16.0'
dependencies:
  - name: frontend
    condition: frontend.enabled
    version: 0.1.0
    repository: file://../apps/frontend/chart
